source 'https://rubygems.org/'
#source 'file:///home/pqr/work/rubygems/'
#source 'file:///media/laila/MARIO_64/rubygems/'

gem 'rails', '5.2.4.6'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails', '>= 4.0.1'
gem 'turbolinks', '>= 2.5.3'
gem 'jbuilder', '~> 1.2'
gem 'thin'
gem 'devise', '>= 4.4.2'
gem 'twitter-bootstrap-rails', '>= 3.2.2'
gem 'less-rails', '>= 2.7.0'
gem 'better_errors'
gem 'binding_of_caller'
gem 'web-console', '>= 2.2.1'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
