source 'file:///media/laila/MARIO_64/rubygems/'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'thin'
gem 'devise'
gem 'twitter-bootstrap-rails'
gem 'less-rails'
gem 'better_errors'
gem 'binding_of_caller'
gem 'web-console'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
